name: Deploy Changes

on: 
  push:
    branches:
      - 'main'

jobs:
  aws:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        working-directory: cloud
        run: terraform init
      - name: Terraform Plan
        working-directory: cloud
        run: |
          terraform plan \
          -var cloudflare_api_token="$CLOUDFLARE_API_TOKEN" \
          -var aws_access_key="$AWS_ACCESS_KEY_ID" \
          -var aws_secret_access_key="$AWS_SECRET_ACCESS_KEY" \
          -var aws_region="$AWS_DEFAULT_REGION"
      - name: Terraform Apply
        working-directory: cloud
        run: |
          terraform apply --auto-approve \
          -var cloudflare_api_token="$CLOUDFLARE_API_TOKEN" \
          -var aws_access_key="$AWS_ACCESS_KEY_ID" \
          -var aws_secret_access_key="$AWS_SECRET_ACCESS_KEY" \
          -var aws_region="$AWS_DEFAULT_REGION"