name: Scheduled Deployment

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  cloudflare:
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
    steps:
      - name: Deploy
        run: scripts/deploy.sh