name: Test Changes

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $AWS_DEFAULT_REGION
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install Python dependencies
        working-directory: lambda
        run: python3 -m pip install -r requirements.txt --break-system-packages
      - name: Run Test
        working-directory: lambda
        env:
          BLOOP: ${{ secrets.BLOOP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: python3 test_handler.py